// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tXTYCQMcFRriEHeNaPTHe7
// Component: XpeFIiBi7NnY

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: t4Ewn2gBSIli/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Statistic from "../../Statistic"; // plasmic-import: BR6TGahQO5AP/component

import { useScreenVariants as useScreenVariantswtDzL3SdIaL } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WtDzL_3SDIaL/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_tmg_demo.module.css"; // plasmic-import: tXTYCQMcFRriEHeNaPTHe7/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: XpeFIiBi7NnY/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 8Ydc_EtyRQKt/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: fV2xAdFtCCM7/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: NpEGyspG1WV_/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: mYDiiUwNMA_x/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: uNTZAlN07UAX/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: g0aZxbzKHlNV/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  homepage?: p.Flex<"div">;
  menu?: p.Flex<"div">;
  menuElements?: p.Flex<"div">;
  heroCta2?: p.Flex<typeof Button2>;
  homeHero?: p.Flex<"section">;
  heroText?: p.Flex<"h1">;
  span?: p.Flex<"span">;
  heroDescription?: p.Flex<"div">;
  heroCta?: p.Flex<typeof Button2>;
  columns?: p.Flex<"section">;
  clients?: p.Flex<"section">;
  imageGrid?: p.Flex<"div">;
  background2?: p.Flex<"div">;
  copy?: p.Flex<"div">;
  checklist?: p.Flex<"section">;
  foreground?: p.Flex<"div">;
  testimonials?: p.Flex<"section">;
  sliderCarousel2?: p.Flex<typeof SliderWrapper>;
  section?: p.Flex<"section">;
  medical?: p.Flex<"section">;
  _3Columns?: p.Flex<"div">;
  amt?: p.Flex<"div">;
  amt2?: p.Flex<"div">;
  amt3?: p.Flex<"div">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: p.generateOnMutateForSpec(
          "currentSlide",
          SliderWrapper_Helpers
        )
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswtDzL3SdIaL()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"homepage"}
          data-plasmic-override={overrides.homepage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.homepage
          )}
          id={"testimonials"}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"menu"}
            data-plasmic-override={overrides.menu}
            hasGap={true}
            className={classNames(projectcss.all, sty.menu)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"menuElements"}
              data-plasmic-override={overrides.menuElements}
              hasGap={true}
              className={classNames(projectcss.all, sty.menuElements)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jt5Sm)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                src={{
                  src: "/plasmic/tmg_demo/images/tmgIconpng.png",
                  fullWidth: 64,
                  fullHeight: 64,
                  aspectRatio: undefined
                }}
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__o4Rsw)}
              >
                <Button2
                  className={classNames("__wab_instance", sty.button2__mfYp)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg___6DwpF)}
                      role={"img"}
                    />
                  }
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__ck3U9)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aVfAp
                    )}
                  >
                    {"What We Do"}
                  </div>
                </Button2>
                <Button2
                  className={classNames("__wab_instance", sty.button2__wwR6I)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__oWyq8)}
                      role={"img"}
                    />
                  }
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__j8Ykx)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qxRi4
                    )}
                  >
                    {"Case Studies"}
                  </div>
                </Button2>
                <Button2
                  data-plasmic-name={"heroCta2"}
                  data-plasmic-override={overrides.heroCta2}
                  className={classNames("__wab_instance", sty.heroCta2)}
                  color={"softSand"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__orDxC)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                >
                  {"Let's Talk"}
                </Button2>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <section
            data-plasmic-name={"homeHero"}
            data-plasmic-override={overrides.homeHero}
            className={classNames(projectcss.all, sty.homeHero)}
            id={"homeHero"}
          >
            <h1
              data-plasmic-name={"heroText"}
              data-plasmic-override={overrides.heroText}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.heroText
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"AN AGENCY CRAFTED\nBY ENTREPRENEURS\n"}
                </React.Fragment>
                {
                  <span
                    data-plasmic-name={"span"}
                    data-plasmic-override={overrides.span}
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.span
                    )}
                  >
                    {"FOR ENTREPRENEURS"}
                  </span>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h1>
            <div
              data-plasmic-name={"heroDescription"}
              data-plasmic-override={overrides.heroDescription}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heroDescription
              )}
            >
              {
                "Thela Media Group (TMG) was founded in 2010 with the goal of helping businesses of all sizes and industries achieve their marketing goals and reach their target audiences through innovative and effective strategies. Since then, we have grown into a full-service marketing and advertising agency with a team of experienced professionals and a proven track record of success."
              }
            </div>
            <Button2
              data-plasmic-name={"heroCta"}
              data-plasmic-override={overrides.heroCta}
              className={classNames("__wab_instance", sty.heroCta)}
              color={"softSand"}
              endIcon={
                <Icon38Icon
                  className={classNames(projectcss.all, sty.svg__hBjr2)}
                  role={"img"}
                />
              }
              showEndIcon={true}
            >
              {"Let's Talk"}
            </Button2>
          </section>
          <section
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__ytLic
              )}
            >
              {"What We Do"}
            </h2>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__dQdhn)}
            >
              <div className={classNames(projectcss.all, sty.column__v2XK)}>
                <div className={classNames(projectcss.all, sty.columns__nAqvg)}>
                  <div className={classNames(projectcss.all, sty.column__elDl)}>
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__gwQGj)}
                      role={"img"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___3SgRu)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__m3UPi
                      )}
                    >
                      {"Marketing Strategy & Implementation"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5HhXy
                      )}
                    >
                      {"This is where block text goes about strategy. "}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__aNw0)}>
                <div className={classNames(projectcss.all, sty.columns__hG8Uk)}>
                  <div
                    className={classNames(projectcss.all, sty.column__nTl2A)}
                  >
                    <Icon5Icon
                      className={classNames(projectcss.all, sty.svg__wVix7)}
                      role={"img"}
                    />
                  </div>
                  <div className={classNames(projectcss.all, sty.column__ucjY)}>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__bZj
                      )}
                    >
                      {"Full-Scale Creative Development"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wiotx
                      )}
                    >
                      {"This is where block text goes about strategy. "}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__mDjcO)}>
                <div className={classNames(projectcss.all, sty.columns__b1Bmo)}>
                  <div
                    className={classNames(projectcss.all, sty.column__t9P1L)}
                  >
                    <Icon6Icon
                      className={classNames(projectcss.all, sty.svg__xGdQ7)}
                      role={"img"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__wqJxZ)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__gHDxf
                      )}
                    >
                      {"Omni-Channel Advertising Deployment"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kSkzV
                      )}
                    >
                      {"This is where block text goes about strategy. "}
                    </div>
                  </div>
                </div>
              </div>
            </p.Stack>
          </section>
          <section
            data-plasmic-name={"clients"}
            data-plasmic-override={overrides.clients}
            className={classNames(projectcss.all, sty.clients)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2___4RNtx
              )}
            >
              {"Trusted By 600+ Companies Worldwide"}
            </h2>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___4UlzU)}
            >
              <div className={classNames(projectcss.all, sty.column__h1DO2)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rSya3)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/Forcepoint-Logo.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___7NYpq)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ie7Sx)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2023/02/Jecobra-Logo.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hlEG)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mQaLs)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2023/02/auntie-annes.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wBNpM)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mDyhm)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/Qualico-logo-2.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__qXdDz)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jrbM5)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/nb-capital-logo.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___32EM)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5H7K)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/Artboard-3amt.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__zVYw)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___4YuMy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2023/02/restart-logo.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__kXDyO)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__geyzG)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/THS-Logo.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__aXghz)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bTptI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2021/11/Artboard-1-copy@2x.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__uGfVw)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wTOW)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://theprevivor-v1685545382.websitepro-cdn.com/wp-content/uploads/2019/09/Logo-Black-Transparent-e1574326461251.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__fa7Oj)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gLjW)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://wellcellglobal.com/wp-content/uploads/2023/12/WellCellGlobalLogo-1.png"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mplzl)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rcIm)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                />
              </div>
            </p.Stack>
          </section>
          <p.Stack
            as={"div"}
            data-plasmic-name={"imageGrid"}
            data-plasmic-override={overrides.imageGrid}
            hasGap={true}
            className={classNames(projectcss.all, sty.imageGrid)}
          >
            <div className={classNames(projectcss.all, sty.columns__f00V1)}>
              <div className={classNames(projectcss.all, sty.column__qbodC)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yuUnU)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"320px"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  src={
                    "https://www.thelamedia.com/wp-content/uploads/2023/01/marketing-campaign-41-1146x1536.jpg"
                  }
                />

                <div
                  data-plasmic-name={"background2"}
                  data-plasmic-override={overrides.background2}
                  className={classNames(projectcss.all, sty.background2)}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__yoJHu)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nxBom)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"copy"}
                    data-plasmic-override={overrides.copy}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.copy)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__skYbl)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vDLlD
                        )}
                      >
                        {"OUR BACKGROUND"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ev1V
                        )}
                      >
                        {"Full Service At Scale"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rNr1P
                        )}
                      >
                        {
                          "We pride ourselves on our ability to craft and implement comprehensive strategies that deliver real results for our clients. \n\nAs a high-end and exclusive firm, we have a proven track record of success working with top companies in industries such as healthcare, real estate, energy, and fintech to name a few.  "
                        }
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zJpK3
                        )}
                        color={"sand"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jFpwN
                            )}
                            role={"img"}
                          />
                        }
                        showEndIcon={true}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uIt5K
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o6NKn
                          )}
                        >
                          {"Let's Talk"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>
            </div>
          </p.Stack>
          <p.Stack
            as={"section"}
            data-plasmic-name={"checklist"}
            data-plasmic-override={overrides.checklist}
            hasGap={true}
            className={classNames(projectcss.all, sty.checklist)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground)}
            >
              <div className={classNames(projectcss.all, sty.column__q3DDi)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__otCfF)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__djEfs
                    )}
                  >
                    {"Freedoms"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ztiBi
                    )}
                  >
                    {"Open by design"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u9HuP
                    )}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>
                </p.Stack>
              </div>
              <div className={classNames(projectcss.all, sty.column__isJhi)}>
                <div className={classNames(projectcss.all, sty.freeBox__z62L0)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__x9UKp)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tv0Ad
                      )}
                    >
                      {"Built on capability"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__gOr0L)}
                      role={"img"}
                    />
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___6XmMs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___38RS
                      )}
                    >
                      {"Highly energetic"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__iEdFk)}
                      role={"img"}
                    />
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nZf3N)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z6JXc
                      )}
                    >
                      {"100% transparency and accountability"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg___1Spn)}
                      role={"img"}
                    />
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zUfNm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dePkn
                      )}
                    >
                      {"Refreshing clarity"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__bLfZf)}
                      role={"img"}
                    />
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__f3Xmi)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7PbL0
                      )}
                    >
                      {"Modern results"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__uSuRk)}
                      role={"img"}
                    />
                  </p.Stack>
                </div>
              </div>
            </p.Stack>
          </p.Stack>
          <section
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.columns__ybObN)}>
              <div className={classNames(projectcss.all, sty.column___0JEUh)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__mdY1Q
                  )}
                >
                  {"What Our Clients Think:"}
                </h2>
              </div>
              <div className={classNames(projectcss.all, sty.column__hXuWl)}>
                <div className={classNames(projectcss.all, sty.freeBox__y0Lu0)}>
                  {(() => {
                    const child$Props = {
                      beforeChange:
                        p.generateStateOnChangePropForCodeComponents(
                          $state,
                          "currentSlide",
                          ["sliderCarousel2", "currentSlide"],
                          SliderWrapper_Helpers
                        ),
                      centerMode: false,
                      className: classNames(
                        "__wab_instance",
                        sty.sliderCarousel2
                      ),
                      dots: false,
                      initialSlide: p.generateStateValueProp($state, [
                        "sliderCarousel2",
                        "currentSlide"
                      ]),
                      ref: ref => {
                        $refs["sliderCarousel2"] = ref;
                      },
                      sliderScopeClassName: sty["sliderCarousel2__slider"]
                    };
                    p.initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "currentSlide",
                          plasmicStateName: "sliderCarousel2.currentSlide"
                        }
                      ],
                      [],
                      SliderWrapper_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <SliderWrapper
                        data-plasmic-name={"sliderCarousel2"}
                        data-plasmic-override={overrides.sliderCarousel2}
                        {...child$Props}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__whQtJ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__om0D6
                            )}
                          >
                            {
                              '"We engaged 5 different digital marketing agencies whom promised a lot, but failed to deliver.  By the end of my first meeting with TMG, I was impressed with their depth of knowledge and subject matter expertise.  TMG\'s approach to business can be expressed in 2 words, trusted partnership.  We were absolutely delighted with the business results TMG helped us achieve."'
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rbv7R
                            )}
                          >
                            {"Carl\nCMO - Fintech Startup"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hyqdw
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__o3Nuj
                            )}
                          >
                            {
                              '"Thela Media Group\u2019s reputation management system has helped us catch 100% of the actionable feedback that ends up online instead of in our team\u2019s hands. They\u2019ve never missed a thing, work 24/7, and have increased our response velocity to just under the speed of light!"'
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eaCL
                            )}
                          >
                            {"Mandy\nCEO - Corporate Property Management"}
                          </div>
                        </div>
                      </SliderWrapper>
                    );
                  })()}
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section, "stats-area")}
          >
            <div className={classNames(projectcss.all, sty.columns__zWpuE)}>
              <div className={classNames(projectcss.all, sty.column__whQyF)}>
                <Statistic
                  className={classNames("__wab_instance", sty.statistic__bsax4)}
                  number={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sZlmZ
                      )}
                    >
                      {"3,193"}
                    </div>
                  }
                  unit={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Qddx
                      )}
                    >
                      {"Active Users"}
                    </div>
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__o93KI)}>
                <Statistic
                  className={classNames("__wab_instance", sty.statistic__r73Do)}
                  number={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Fxl
                      )}
                    >
                      {"3,193"}
                    </div>
                  }
                  unit={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4EmrX
                      )}
                    >
                      {"Active Users"}
                    </div>
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__lDoDz)}>
                <Statistic
                  className={classNames("__wab_instance", sty.statistic__mSwAz)}
                  number={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ijLy7
                      )}
                    >
                      {"3,193"}
                    </div>
                  }
                  unit={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6BghD
                      )}
                    >
                      {"Active Users"}
                    </div>
                  }
                />
              </div>
            </div>
          </section>
          <p.Stack
            as={"section"}
            data-plasmic-name={"medical"}
            data-plasmic-override={overrides.medical}
            hasGap={true}
            className={classNames(projectcss.all, sty.medical)}
          >
            <div
              className={classNames(
                projectcss.all,
                sty.freeBox__yOjOv,
                "elevation"
              )}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___7EXZp
                )}
              >
                {"Medical Industry"}
              </h2>
              <p.Stack
                as={"div"}
                data-plasmic-name={"_3Columns"}
                data-plasmic-override={overrides._3Columns}
                hasGap={true}
                className={classNames(projectcss.all, sty._3Columns)}
              >
                <div
                  data-plasmic-name={"amt"}
                  data-plasmic-override={overrides.amt}
                  className={classNames(projectcss.all, sty.amt)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__c85OY)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dbCCp)}
                      displayHeight={"auto"}
                      displayMaxHeight={"90px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://www.thelamedia.com/wp-content/uploads/2021/11/Artboard-3amt.png"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w3Pi3
                      )}
                    >
                      {
                        "Strategy and multi-channel advertising implementation for clinical trial patient recruitment across multiple geographies."
                      }
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"amt2"}
                  data-plasmic-override={overrides.amt2}
                  className={classNames(projectcss.all, sty.amt2)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dvoEo)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__j2AyT)}
                      displayHeight={"auto"}
                      displayMaxHeight={"90px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://wellcellglobal.com/wp-content/uploads/2023/12/WellCellGlobalLogo-1.png"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e4Ptt
                      )}
                    >
                      {
                        "Brand standards implementation and comprehensive marketing & advertising strategy for patented protocol."
                      }
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"amt3"}
                  data-plasmic-override={overrides.amt3}
                  className={classNames(projectcss.all, sty.amt3)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wxktk)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wM4L)}
                      displayHeight={"auto"}
                      displayMaxHeight={"90px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://familymedicineaustin.com/wp-content/uploads/2021/03/logo_new__1___1_-1-400x84.png"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yPXxs
                      )}
                    >
                      {
                        "Fractional CMO implementation, website development and focused new patient recruitment for ancillary service lines."
                      }
                    </div>
                  </p.Stack>
                </div>
              </p.Stack>
            </div>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  homepage: [
    "homepage",
    "menu",
    "menuElements",
    "heroCta2",
    "homeHero",
    "heroText",
    "span",
    "heroDescription",
    "heroCta",
    "columns",
    "clients",
    "imageGrid",
    "background2",
    "copy",
    "checklist",
    "foreground",
    "testimonials",
    "sliderCarousel2",
    "section",
    "medical",
    "_3Columns",
    "amt",
    "amt2",
    "amt3"
  ],
  menu: ["menu", "menuElements", "heroCta2"],
  menuElements: ["menuElements", "heroCta2"],
  heroCta2: ["heroCta2"],
  homeHero: ["homeHero", "heroText", "span", "heroDescription", "heroCta"],
  heroText: ["heroText", "span"],
  span: ["span"],
  heroDescription: ["heroDescription"],
  heroCta: ["heroCta"],
  columns: ["columns"],
  clients: ["clients"],
  imageGrid: ["imageGrid", "background2", "copy"],
  background2: ["background2"],
  copy: ["copy"],
  checklist: ["checklist", "foreground"],
  foreground: ["foreground"],
  testimonials: ["testimonials", "sliderCarousel2"],
  sliderCarousel2: ["sliderCarousel2"],
  section: ["section"],
  medical: ["medical", "_3Columns", "amt", "amt2", "amt3"],
  _3Columns: ["_3Columns", "amt", "amt2", "amt3"],
  amt: ["amt"],
  amt2: ["amt2"],
  amt3: ["amt3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  homepage: "div";
  menu: "div";
  menuElements: "div";
  heroCta2: typeof Button2;
  homeHero: "section";
  heroText: "h1";
  span: "span";
  heroDescription: "div";
  heroCta: typeof Button2;
  columns: "section";
  clients: "section";
  imageGrid: "div";
  background2: "div";
  copy: "div";
  checklist: "section";
  foreground: "div";
  testimonials: "section";
  sliderCarousel2: typeof SliderWrapper;
  section: "section";
  medical: "section";
  _3Columns: "div";
  amt: "div";
  amt2: "div";
  amt3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homepage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("homepage"),
  {
    // Helper components rendering sub-elements
    menu: makeNodeComponent("menu"),
    menuElements: makeNodeComponent("menuElements"),
    heroCta2: makeNodeComponent("heroCta2"),
    homeHero: makeNodeComponent("homeHero"),
    heroText: makeNodeComponent("heroText"),
    span: makeNodeComponent("span"),
    heroDescription: makeNodeComponent("heroDescription"),
    heroCta: makeNodeComponent("heroCta"),
    columns: makeNodeComponent("columns"),
    clients: makeNodeComponent("clients"),
    imageGrid: makeNodeComponent("imageGrid"),
    background2: makeNodeComponent("background2"),
    copy: makeNodeComponent("copy"),
    checklist: makeNodeComponent("checklist"),
    foreground: makeNodeComponent("foreground"),
    testimonials: makeNodeComponent("testimonials"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    section: makeNodeComponent("section"),
    medical: makeNodeComponent("medical"),
    _3Columns: makeNodeComponent("_3Columns"),
    amt: makeNodeComponent("amt"),
    amt2: makeNodeComponent("amt2"),
    amt3: makeNodeComponent("amt3"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
